version: 2
jobs:
  checkout:
    docker:
      - image: circleci/node:12-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/repo
          paths: .

  install:
    docker:
      - image: circleci/node:12-browsers
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - v2-yarn-dependencies-{{ checksum "yarn.lock" }}
            - v2-yarn-dependencies- # fallback to latest cache if no exact match is found
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: v2-yarn-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - flow-typed
            - .yarn-cache

  build:
    docker:
      - image: circleci/node:12-browsers
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - v2-yarn-dependencies-{{ checksum "yarn.lock" }}
            - v2-yarn-dependencies- # fallback to latest cache if no exact match is found
      - run: DEBUG=abstract:* yarn flow

  lint:
    docker:
      - image: circleci/node:12-browsers
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - v2-yarn-dependencies-{{ checksum "yarn.lock" }}
            - v2-yarn-dependencies- # fallback to latest cache if no exact match is found
      - run: DEBUG=abstract:* yarn check-ts-types

  lint:
    docker:
      - image: circleci/node:12-browsers
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - v2-yarn-dependencies-{{ checksum "yarn.lock" }}
            - v2-yarn-dependencies- # fallback to latest cache if no exact match is found
      - run: DEBUG=abstract:* yarn lint

  test:
    docker:
      - image: circleci/node:12-browsers
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - v2-yarn-dependencies-{{ checksum "yarn.lock" }}
            - v2-yarn-dependencies- # fallback to latest cache if no exact match is found
      - run: DEBUG=abstract:* yarn test

  deploy:
    docker:
      - image: circleci/node:12-browsers
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - v2-yarn-dependencies-{{ checksum "yarn.lock" }}
            - v2-yarn-dependencies- # fallback to latest cache if no exact match is found
      - run: sh .circleci/deploy

  publish:
    docker:
      - image: circleci/node:12-browsers
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - v2-yarn-dependencies-{{ checksum "yarn.lock" }}
            - v2-yarn-dependencies- # fallback to latest cache if no exact match is found
      - run: npm publish --access public

tagged: &tagged
  filters:
    tags:
      only: /^v.*/
    branches:
      ignore: /.*/

any: &any
  filters:
    tags:
      only: /.*/

workflows:
  version: 2
  build:
    jobs:
      - checkout:
          <<: *any
      - install:
          <<: *any
          requires:
            - checkout
      - build:
          <<: *any
          requires:
            - install
      - lint:
          <<: *any
          requires:
            - install
      - test:
          <<: *any
          requires:
            - install
      - deploy:
          <<: *any
          requires:
            - build
            - lint
            - test
          filters:
            branches:
              only: docs
      - publish:
          <<: *tagged
          requires:
            - build
            - lint
            - test
